### ISSUE TITLE
Access to training data

### ISSUE THREAD

**Issue by mukesh-mehta** [Rutvik-Trivedi/Gujarati-NLP-Toolkit#1]
Where can I access the training data??

**Comment by Rutvik-Trivedi** [comment]
Sorry for the (very) late reply. For this POS tagger, I had used a small sample training data. But if you need to implement the POS tagger for yourself, IIT Bombay might have something. I would suggest contacting them for the dataset if you require it.

**Comment by mukesh-mehta** [comment]
ok, thanks
